# Appveyor.yml
---

version: '{build}'

build: off

environment:
  matrix:
    - PYTHON: "C:/Python37"
      TOXENV: "py37"

    - PYTHON: "C:/Python38"
      TOXENV: "py38"

init:
  - "ECHO %TOXENV%"
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"

install:
  - "%PYTHON%/python.exe -m pip install --upgrade wheel pip setuptools virtualenv"
  - "%PYTHON%/python.exe -m pip install tox"
  - "%PYTHON%/python.exe -m pip install -e .[test]"

test_script:
  - "%PYTHON%/Scripts/pip.exe --version"
  - "%PYTHON%/Scripts/virtualenv.exe --version"
  - "%PYTHON%/Scripts/tox.exe --version"
  - "%PYTHON%/Scripts/tox.exe -- -v"

...
