#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Vim: set ft=python:
"""Set up pdb or ipdb.

.. code-block:: console

    $: ipdb3 -h

.. code-block:: none

    usage: python -m ipdb [-c command] ... pyfile [arg] ...
    Debug the Python program given by pyfile.
    Initial commands are read from .pdbrc files in your home directory
    and in the current directory, if they exist.  Commands supplied with
    -c are executed after commands from .pdbrc files.
    To let the script run until an exception occurs, use "-c continue".
    To let the script run up to a given line X in the debugged file, use
    "-c 'until X'"
    ipdb version 0.10.3.

"""
try:
    import pyreadline
except:
    try:
        import jedi
    except:
        pass
    else:
        from jedi.utils import setup_readline
        setup_readline()
        del jedi

# https://github.com/python/cpython/blob/3.7/Lib/pdb.py#L1380
# in the do_alias() function it mentions some examples and they sounded like
# useful alias to tack on!

# Print instance variables (usage "pi classInst")
alias pi for k in % 1.__dict__.keys(): print("%1.", k, "=", % 1.__dict__[k])  # noqa
# # Print instance variables in self
alias ps pi self

# # Apr 07, 2019
# # How in the world have I gone this long without noticing this isn't set up
alias ? pinfo
# # Kinda sucks now only ?func is valid not func?
alias ?? pinfo2
