{% set name = "dynamic-ipython" %}

package:
    name: "{{ name|lower }}"
    version: "{{ GIT_DESCRIBE_TAG }}"

source:
  path: ../

build:
    number: 0
    script: "{{ PYTHON }} -m pip install {{ PWD }} --no-deps --ignore-installed -vv "

requirements:
    run:
        - IPython 7.10.2.*
        - numpy {{ numpy }}
        - python >=3.7.4
        - wheel  <=0.33.6
    host:
        - python >=3.7
        - pip  >=19.2.3

test:
  imports:
    - default_profile
    - default_profile.sphinxext
    - default_profile.extensions
    - default_profile.utils

about:
  home: "https://farischugthai/dynamic-ipython.io"
  license: "MIT"
  license_family: "MIT"
  license_file: "../LICENSE"
