{% set name = "dyanmic-ipython" %}
{% set version = "0.0.2" %}

package:
	name: "{{ name|lower }}"
	version: "{{ version }}"

source:
	url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
	sha256: ":todo:"

build:
	number: 0
	script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.8.28 0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libgcc-ng 9.1.0 hdf63c60_0
        - libffi 3.2.1 hd88cf55_4
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_2
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
        - libedit 3.1.20181209 hc058e9b_0
        - readline 7.0 h7b6447c_5
        - tk 8.6.8 hbc83047_0
        - sqlite 3.30.0 h7b6447c_0
        - python 3.7.4 h265db76_1
        - certifi 2019.9.11 py37_0
        - setuptools 41.4.0 py37_0
        - wheel 0.33.6 py37_0
        - pip 19.2.3 py37_0
    run:
        - python >=3.7,<3.8.0a0
test:
  imports:
    - default_profile
    - default_profile.sphinxext
    - default_profile.extensions
    - default_profile.utils

about:
  home: "https://farischugthai/dynamic-ipython.io"
  license: "MIT"
  license_family: "MIT"
  license_file: ""
  summary: "IPython: Productive Interactive Computing"
  doc_url: ""
  dev_url: ""

extra:
	recipe-maintainers:
		- your-github-id-here
    copy_test_source_files: true
    final: true
