---

{% set name = "dynamic-ipython" %}
{% set data = load_setup_py_data() %}


package:
  name: "{{ name|lower }}"
  version: {{ data.get('version') }}

source:
  path_url: ../..

build:
  number: 0
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  # "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or
  # "skip: True  # [not win]" to limit to Windows.
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .
  preserve_egg_dir: True
  noarch: python

requirements:
  run:
    - IPython 7.13
    - numpy {{ numpy }}
    - python >=3.7.4
    - wheel  <=0.33.6
    {{ data.get("REQUIRED")  }}

  host:
    - python >=3.7
    - pip  >=19.2.3

test:
  imports:
    - default_profile
    - default_profile.sphinxext
    - default_profile.extensions
    - default_profile.utils

about:
  home: "https://farischugthai/dynamic-ipython.io"
  license: "MIT"
  license_family: "MIT"
  license_file: "../LICENSE"

# Vim: set ft=yaml.htmljinja

...
