name: dynamic-ipython
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.7.4
  - sphinx==2.4.0
  - IPython==7.13.0
  # For documentation building and testing
  - matplotlib>=3
  - pytest>=5.4
  - pip==20.0.1
  - nose
  - numpydoc
